name: Issue and PR Hygiene

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Mark Stale Issues & PRs
        uses: actions/stale@v8
        with:
          days-before-stale: 30
          days-before-close: 7
          stale-issue-label: "stale"
          stale-pr-label: "stale"
          exempt-issue-labels: "keep-open"
          exempt-pr-labels: "keep-open"
          stale-issue-message: "This issue has been automatically marked as stale because it has been inactive for 30 days."
          stale-pr-message: "This pull request has been marked as stale because it has been inactive for 30 days."
          close-issue-message: "This issue has been closed due to inactivity."
          close-pr-message: "This pull request has been closed due to inactivity."

  lock-threads:
    runs-on: ubuntu-latest
    steps:
      - name: Lock Closed Issues & PRs
        uses: dessant/lock-threads@v4
        with:
          issue-inactive-days: 60
          pr-inactive-days: 60
          process-only: issues,pull_requests
          exclude-any-labels: 'keep-open'
          lock-reason: "resolved"